### PR TITLE
Fix wildly-off coordinates for keypoints with PiecewiseAffine

### PR DESCRIPTION
**Pull request by r1cc4rdo**
This avoid the fallback to image transformations for keypoints in PiecewiseAffine, dramatically improving performance.

As noted in the original code, I sporadically experienced "augmented coordinates [being] wildly off". Upon debugging, I realized that despite the np.clip calls some keypoints where still out-of-bounds and being returned as (-1, -1) as a result.

I originally suspected lines #3234, #3235 in geometric.py to be off-by-one (i.e. x = np.linspace(0, augmentable_shape[1] - 1, nb_cols)) but that did not solve the problem for me.

What worked for me was keeping corners in place and constraining intermediate points on the boundary to only move along it.

### CODE REVIEW

**Comment by aleju** [comment]
Hey, thanks for the help and sorry for the late reply.
I just ran this through a mildly modified version of `checks/check_piecewise_affine.py` and this is the output that I'm getting:
piecewiseaffine

For some keypoints it still seems to be quite off. Strangely, it can be off for some keypoints and accurate for other keypoints within the same image. I don't know what the reason for that is. :neutral_face: 
Did you use a different way to test this?

**Comment by r1cc4rdo** [comment]
I did not experience misalignments in my code.
Let me have a look at `checks/check_piecewise_affine.py` to see if I can reproduce.

**Comment by aleju** [comment]
I had made some small modifications to the file, you can use this one instead:
```python
from __future__ import print_function, division

import numpy as np

import imgaug as ia
import imgaug.random as iarandom
from imgaug import augmenters as iaa

iarandom.seed(5)


def main():
    image = ia.quokka(size=0.5)
    print(image.shape)
    kps = [
        ia.KeypointsOnImage(
            [
                ia.Keypoint(x=123, y=102),
                ia.Keypoint(x=182, y=98),
                ia.Keypoint(x=155, y=134),
                ia.Keypoint(x=-20, y=20),
                ia.Keypoint(x=410, y=95),
            ],
            shape=(image.shape[0], image.shape[1])
        )
    ]
    print("image shape:", image.shape)

    augs = [
        iaa.PiecewiseAffine(scale=0.05),
        iaa.PiecewiseAffine(scale=0.1),
        iaa.PiecewiseAffine(scale=0.2),
        iaa.PiecewiseAffine(scale=0.3)
    ]

    ia.imshow(kps[0].draw_on_image(image))

    print("-----------------")
    print("Random aug per image")
    print("-----------------")
    for aug in augs:
        images_aug = []
        for _ in range(16):
            aug_det = aug.to_deterministic()
            img_aug = aug_det.augment_image(image)
            kps_aug = aug_det.augment_keypoints(kps)[0]
            print(kps_aug)
            img_aug_kps = keypoints_draw_on_image(kps_aug, img_aug, size=5)
            img_aug_kps = np.pad(img_aug_kps, ((1, 1), (1, 1), (0, 0)), mode="constant", constant_values=255)
            images_aug.append(img_aug_kps)
        print(aug.name)
        ia.imshow(ia.draw_grid(images_aug))


def keypoints_draw_on_image(kps, image, color=[0, 255, 0], size=3, copy=True,
                            raise_if_out_of_image=False, border=50):
    if copy:
        image = np.copy(image)

    #image = iaa.pad(image, top=border, right=border, bottom=border, left=border)
    #kps = kps.shift(x=border, y=border)
    #kps.shape = (kps.shape[0] + 2*border, kps.shape[1] + 2*border) + kps.shape[2:]

    return kps.draw_on_image(
        image, color=color, size=size, raise_if_out_of_image=raise_if_out_of_image
    )


if __name__ == "__main__":
    main()

```

**Comment by r1cc4rdo** [comment]
Thanks for the code snippet.
I went to the bottom of it and found what I think is the problem.

quokka_grid

The image above is one of the offending transformations from your script.
Green dots are the source coordinates, green crosses the destination ones.
Here is the same transformation, but using instead two aligned grids, one made of pixels, the other given as coordinates.

dots_grid

After warping, it becomes:

dots_warped

The bottom half of the image shows consistent transformations, the top half however does not.
Here's an annotated version of the same image:

annotated

It looks to me that the Delaunay triangulations for the warp and coordinates transformations have different connectivity, with the misalignment happening whenever there's a flipped edge.
If this is indeed the issue, it's deep inside scikit's code: I did not find any straightforward way to fix it there while looking around.

A second, unrelated problem comes from allowing jitter values so large that some triangles fold on each other. Look at the following annotated image, also from the example script.

bijection_break

Since the PR does not actually solve the problem, I'm fine closing it.

**Comment by r1cc4rdo** [comment]
Adding `self._inverse_tesselation.simplices = self._tesselation.simplices` here [_geometric.py#L893](https://github.com/scikit-image/scikit-image/blob/9aac8495b7b9e50d8660c0e32f2301835bc1ddb2/skimage/transform/_geometric.py#L893) nearly fixes the problem.

Before:
myplot

After:
myplot2

Some coordinates end up disappearing because the hack above does not update the remaining tesselation properties such as neighbors and equations (-_-')

**Comment by aleju** [comment]
Hm, interesting how changing `_inverse_tesselation.simplices` affects the results. Not sure what to do with that insight yet.

I think last time I looked into this issue, I came to the speculative conclusion that scikit-image might expect much smoother transformations than what imgaug requests. I.e. that imgaug randomly moves points around (each one independently), which can lead to very dissimilar movements between neighbouring points, while scikit-image expects very similar movements between neighbouring points. At least the example that they had on their website to showcase coordinate transformation und PiecewiseAffine followed that style.

**Comment by r1cc4rdo** [comment]
My understanding is that this is bug is scikit's code that was never discovered because it is often exercised on a larger/denser number of corresponding points, resulting in imperceptible errors (and smoother deformations, as you said).

Closing the PR, thank you for having a look!

**Pull request closed without merging**
