### PR TITLE
Add capability of transformaing non uint8 images

### PR DESCRIPTION
**Pull request by wkentaro**
## Motivation

I'm working for image segmentation problems, and would like to augument label images that as int32 dtype not uint8.
In that case, it is necessary to use `mode=0` (NEAREST) and `preserve_range=True` with scikit-image.

### CODE REVIEW

**Comment by wkentaro** [comment]
image

```
#!/usr/bin/env python

import imgaug.augmenters as iaa
import skimage.io
import skimage.color
import PIL.Image
import numpy as np


seq = iaa.Sequential([
    iaa.Fliplr(0.5),
    iaa.Flipud(0.5),
    iaa.Affine(
        scale={'x': (0.9, 1.1), 'y': (0.9, 1.1)},
        translate_px={'x': (-16, 16), 'y': (-16, 16)},
        rotate=(-10, 10),
        shear=(-16, 16),
        order=0,
        cval=-1,
        mode='constant',
    ),
])

vizs = []

img = skimage.io.imread('./2007_000129.jpg')
lbl = np.array(PIL.Image.open('./2007_000129.png'), dtype=np.int32)
lbl[lbl == 255] = -1

assert img.dtype == np.uint8
assert lbl.dtype == np.int32
lbl_viz = lbl.copy()
mask = lbl == -1
lbl_viz[mask] = 0
viz = skimage.color.label2rgb(lbl_viz, img, bg_label=0)
viz[mask] = 0
vizs.append(viz)

for i in xrange(15):
    seq = seq.to_deterministic()
    img_aug = seq.augment_images([img])[0]
    lbl_aug = seq.augment_images([lbl])[0]
    mask = lbl_aug == -1
    lbl_aug[mask] = 0
    viz = skimage.color.label2rgb(lbl_aug, img_aug, bg_label=0)
    viz[mask] = 0
    vizs.append(viz)

import util
viz = util.image.tile(vizs, (4, 4))
skimage.io.imsave('tile.jpg', viz)
```

**Comment by aleju** [comment]
Why did you delete the check `assert len(image.shape) == 3, ...`?
If your mask is only in the form `height x width` and not `height x width x 1` you can just temporarily add a channel via `mask = mask[:, :, np.newaxis]` and remove it after the augmentation via `mask_aug = np.squeeze(mask_aug)`.

**Comment by wkentaro** [comment]
I added assertion for the number of dimension for 2 or 3.
I think that temporal channel change makes code complicated, and 2 dimensional image should be supported in imgaug.
Because there are many cases we have a single-channel image: mask, label, gray, and depth image.

**Comment by aleju** [comment]
Merged.

**Pull request merged**
