### PR TITLE
Add fit_output (False/True) option to Affine augmenters

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/aleju/imgaug/pull/50

## Note

There is no longer a dependency on the change of scikit-image.

## Sample

sample_affine_fit_output

```
#!/usr/bin/env python

from scipy.misc import face
from itertools import product

import imgaug.augmenters as iaa
import matplotlib.pyplot as plt


img = face()


i = 0
i += 1
plt .subplot(2, 4, i)
plt .imshow(img)
plt .title('original')
for fit_output, backend in product([False, True], ['auto', 'skimage', 'cv2']):
    print(fit_output, backend)

    augmenter = iaa.Affine(
        scale=0.7,
        translate_px=5,
        rotate=60,
        shear=0.1,
        fit_output=fit_output,
        backend=backend,
    )
    img_aug = augmenter.augment_image(img)

    i += 1
    plt .subplot(2, 4, i)
    plt .imshow(img_aug)
    plt .title('fit_output={}, backend={}'.format(fit_output, backend))

plt .show()
```

### CODE REVIEW

**Comment by wkentaro** [comment]
@aleju Could you please review this and instruct me the required changes to make this PR be merged.

**Comment by wkentaro** [comment]
image

image

```
#!/usr/bin/env python

from itertools import product

import imgaug.imgaug as ia
import imgaug.augmenters as iaa
import numpy as np
import matplotlib.pyplot as plt


image = ia.quokka()
heatmap = ia.quokka_heatmap()
keypoints = ia.quokka_keypoints()

for index, dat in enumerate([image, heatmap, keypoints]):
    i = 0
    i += 1
    plt.figure(figsize=(20, 10))
    plt .subplot(2, 4, i)
    if isinstance(dat, ia.HeatmapsOnImage):
        plt .imshow(dat.draw()[0])
    elif isinstance(dat, ia.KeypointsOnImage):
        plt .imshow(dat.draw_on_image(image, size=20))
    else:
        plt .imshow(dat)
    plt .title('original')
    for fit_output, backend in product([False, True], ['auto', 'skimage', 'cv2']):
        print(fit_output, backend)

        augmenter = iaa.Affine(
            scale=0.7,
            translate_px=5,
            rotate=60,
            shear=0.1,
            fit_output=fit_output,
            backend=backend,
        )
        if isinstance(dat, ia.HeatmapsOnImage):
            dat_aug = augmenter.augment_heatmaps([dat])[0]
        elif isinstance(dat, ia.KeypointsOnImage):
            dat_aug = augmenter.augment_keypoints([dat])[0]
        else:
            dat_aug = augmenter.augment_image(dat)

        i += 1
        plt .subplot(2, 4, i)
        if isinstance(dat, ia.HeatmapsOnImage):
            plt .imshow(dat_aug.draw()[0])
        elif isinstance(dat, ia.KeypointsOnImage):
            image_aug = augmenter.augment_image(image)
            plt .imshow(dat_aug.draw_on_image(image_aug, size=20))
        else:
            plt .imshow(dat_aug)
        plt .title('fit_output={}, backend={}'.format(fit_output, backend))

    # plt .show()
    plt.savefig('%d.jpg' % index)
```

**Comment by wkentaro** [comment]
I updated the code as your suggestions. Could you review again?

**Comment by aleju** [comment]
Perfect -- this is now merged into master. Thanks for the help and for writing the heatmaps/keypoints parts too!

**Comment by wkentaro** [comment]
Thanks!

**Pull request merged**
